# https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/configuration-options-for-dependency-updates
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-patch"]

    commit-message:
      prefix: ci
    labels: ["skip changelog"]

  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    allow:
      - dependency-type: "all"
    versioning-strategy: "lockfile-only"
    require-dependency-file: true
    require-dependency-type: "production"
    groups:
      dev-dependencies:
        patterns:
          - "*"
        exclude-patterns:
          - "poetry"
    commit-message:
      prefix: "poetry"
      include: "scope"