name: Verification

on:
  push:
    branches: [ master ]
    paths:
      - '**/*.py'
  pull_request:
    branches: [ master ]
    paths:
      - '**/*.py'

jobs:

  verify:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ['3.7', '3.8', '3.9', '3.10', '3.11', '3.12']

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: cache-pip
          restore-keys: |
            cache-pip

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ruff

      - name: Cache Ruff
        uses: actions/cache@v4
        with:
          path: ~/.cache/ruff
          key: cache-ruff
          restore-keys: |
            cache-ruff

      - name: Run Ruff checks
        run: |
          ruff_format_status=0
          ruff_lint_status=0
          
          ruff format --check . || ruff_format_status=$?
          ruff check . --diff || ruff_lint_status=$?
          
          if [ $ruff_format_status -ne 0 ] || [ $ruff_lint_status -ne 0 ]; then
            exit 1
          fi

      - name: Install dependencies
        run: |
          pip install poetry
          poetry install

      - name: Run tests
        run: poetry run pytest
